sudo: false
language: node_js
node_js:
- '6'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
cache:
  directories:
    - node_modules
before_install:
  - npm i -g npm@^2.0.0
before_script:
  - npm prune
  - npm run ready-env
script: 
  - npm run build
after_success:
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
